### ISSUE TITLE
items.sh returns error while copying folder

### ISSUE THREAD

**Issue by bachng2017** [bachng2017/RENAT#14]
confirmed on python3 and mounted NFS
```
Traceback (most recent call last):
  File "/home/h.nguyen/work/renat/tools/item.sh", line 113, in <module>
    shutil.copytree(TEMPLATE, NAME)
  File "/usr/lib64/python3.6/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error:
...
```

**Comment by bachng2017** [comment]
this is caused by a shutil issue  https://bugs.python.org/issue17076
item.sh returns error but the target item folder is created successfully.
currently just ignore the errors.

**Comment by bachng2017** [comment]
possibly related to this bug https://bugs.python.org/issue36850

**Comment by bachng2017** [comment]
temporarily deployed a workaround
